# message("hello!! this is test_api.cmake")
message("${CMAKE_CURRENT_LIST_FILE}")
message("${CMAKE_CURRENT_LIST_DIR}")
message("${CMAKE_CURRENT_SOURCE_DIR}")
message("${CMAKE_CURRENT_BINARY_DIR}")
include("${CMAKE_CURRENT_LIST_DIR}/cmake/all.cmake")
