## cmake/sweet_version.cmake
##
## Copyright (c) 2017 ChienYu Lin
##
## Author: ChienYu Lin <cy20lin@gmail.com>
## License: MIT
##

set(SWEET_MAJOR_VERSION 0)
set(SWEET_MINOR_VERSION 0)
set(SWEET_PATCH_VERSION 0)
set(SWEET_TWEAK_VERSION 0)
set(SWEET_VERSION_DESCRIPTION "develop")
set(SWEET_VERSION_NUMBER "${SWEET_MAJOR_VERSION}.${SWEET_MINOR_VERSION}.${SWEET_PATCH_VERSION}")
set(SWEET_VERSION "${SWEET_VERSION_NUMBER}-${SWEET_VERSION_DESCRIPTION}")
